### ISSUE TITLE
Estimate our best-case User Base

### ISSUE THREAD

**Issue by Restuta** [Restuta/rcn.io#11]
Based on the stats we've collected and stats from USA Cycling we can estimate our potential user base.

We can go with the following assumptions (each point reduces given set of all racers):
* most users will be in-between 16 and 45 year old (older folks might not use our app)
* only active racers will be interested (we can define "active" as 15+ races per year)

For example if there are 2000 racers in CA, we might figure out that it's just 1000 of them in-between 16 and 45 year old. Then only 500 of them can be described as active. This means that our potential user base is 500 if all 100% will use our app.

We don't have to have stats for all other states, we can take CA and approximate the rest. So if our user base is only 500/2000 = 25%, then knowing that there are 70000 racers in USA we can calculate total = 70000 * 0.25 = 17500

--

As a result of this issue we need two numbers (post them here for now):
- [x] CA best-case user base
- [x] USA best-case user base

This would allow us to understand how many people theoretically can use our product.

**Comment by Me4ta** [comment]
USA. Active ~ 38 155 (~ 60.2%)
Total 63 377 (USA by states stat sheet).
Active riders 60.2% from all USA riders (74% from responded riders who did the 9 and more events in 2013 year + 5% from non responded riders, since they might be active too)

CA. Active ~ 3 000 (60.2%)
Total 7 500 (from usacycling.org rating list).
Active riders 60.2%, just the same % as in the USA stat.

https://docs.google.com/spreadsheets/d/1gWdb5VPyeVuQVCyz5bUIjCR7B_t7FKfSrZ2709Lu168/edit#gid=1407621024

**Comment by Restuta** [comment]
|USA                      | CA
---------|-----------------------| -------------
Active | 38155 (~60.2%) | ~3000 (60.2%)
Total   | 63377               | 7500

**Comment by Me4ta** [comment]
yep

**Comment by Me4ta** [comment]
**Active is >= 15 events/year.**

           |USA                      | CA
---------|-----------------------| -------------
Active | 28463 (44.9%) | 3368 (44.9%)
Total   | 63377               | 7500

**Comment by Restuta** [comment]
Potential user base 
CA: 3.3k-4.5K
USA: 28K-38K
